services:
  image:
    image: jekyll-github-pages
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "UID=1000"
        - "GID=1000"
        - "JEKYLL_VERSION=3.10.0"
    restart: "no"
    command: exit 0
  bundle:
    image: jekyll-github-pages
    environment:
      - JEKYLL_ENV=development
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    restart: "no"
    entrypoint: [ 'bundle' ]
  npm:
    image: jekyll-github-pages
    environment:
      - JEKYLL_ENV=development
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    restart: "no"
    entrypoint: [ 'npm' ]
  watch:
    image: jekyll-github-pages
    environment:
      - JEKYLL_ENV=development
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    command: >
      sh -c "npx nf start jekyll-watch,tailwind-watch,typescript-watch"
  build:
    image: jekyll-github-pages
    environment:
      - JEKYLL_ENV=production
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    command: >
      sh -c "npx nf run typescript-build &&\
      npx nf run tailwind-build &&\
      npx nf run jekyll-build"
  serve:
    image: jekyll-github-pages
    environment:
      - JEKYLL_ENV=production
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    command: >
      sh -c "npx nf start jekyll-serve"